version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 4dm1n_*
      POSTGRES_DB: tasks
    networks:
      - projecttasks

  test-db:
    image: postgres:13
    ports:
      - 5431:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 4dm1n_*
      POSTGRES_DB: tasks
    networks:
      - projecttasks
networks:
  projecttasks:
